<?php

declare(strict_types=1);

namespace Drupal\collective\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Form handler for API Client add/edit forms.
 *
 * On creation, the token is auto-generated by `ApiClient::preSave()` —
 * this form's only extra job is showing that plaintext exactly once, via
 * a status message, with a clear "will not be shown again" notice, per
 * task 0091. A plain edit (no regeneration) never has a plaintext to
 * show — see `ApiClientRegenerateTokenForm` for the only other place a
 * plaintext ever appears.
 */
class ApiClientForm extends ContentEntityForm {

  /**
   * {@inheritdoc}
   */
  public function form(array $form, FormStateInterface $form_state) {
    $form = parent::form($form, $form_state);

    $form['#prefix'] = '<div class="hivelog-entity-form">';
    $form['#suffix'] = '</div>';
    $form['#attached']['library'][] = 'hivelog/forms';

    if (!$this->entity->isNew()) {
      $form['endpoints'] = [
        '#type' => 'item',
        '#title' => $this->t('API endpoint'),
        '#markup' => '<p>' . $this->t('Context read: <code>GET @contexts_url</code>', [
          '@contexts_url' => Url::fromRoute('collective.api_client.context', [], ['absolute' => TRUE])->toString(),
        ]) . '</p>',
        '#weight' => -10,
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {
    $entity = $this->entity;
    $status = $entity->save();

    if ($status === SAVED_NEW) {
      $plaintext = $entity->getPlainTextToken();
      $this->messenger()->addStatus($this->t('API client %label has been created.', [
        '%label' => $entity->label(),
      ]));
      if ($plaintext) {
        $this->messenger()->addWarning($this->t('Token (copy this now — it will not be shown again): %token', [
          '%token' => $plaintext,
        ]));
      }
    }
    else {
      $this->messenger()->addStatus($this->t('API client %label has been updated.', [
        '%label' => $entity->label(),
      ]));
    }

    $form_state->setRedirectUrl($entity->toUrl());
    return $status;
  }

}
